### ISSUE TITLE
Changes ?

### ISSUE THREAD

**Issue by abataille** [rainlake/node-lightify#1]
If you are open to changes, I did experiment with your approach and have some suggestions:

- I used a patch to get & set the mac add as String.
- I found that when you send a couple of commands in short sequence, not all were executed. So i changed the client.on behavior .
- I missed a reconnect feature in case the Lightly server dropped the connection.

**Comment by frequenc1** [comment]
I'm am very interested in your changes. I was running into the problem just now. I'm trying to figure out how to change the color of a node so instead I was looping through the lights trying to send them all color commands but it was failing after the first light.

**Comment by rainlake** [comment]
Thanks guys. This library is designed for use with another project. Most of
your suggestions are implied there. I will think about it.
Thanks again.

**Comment by rainlake** [comment]
Please send pull request if you can. Thanks

**Comment by abataille** [comment]
Can’t add the pull request. Permissions missing.
Attached is my index.js

**Comment by frequenc1** [comment]
Doesn't seem as if the attachment came along. You should be able to attach them via the github issue thread

**Comment by abataille** [comment]
These are my changes. I have those running with Homebridge and my Osram Lightly platform.
[index.txt](https://github.com/rainlake/node-lightify/files/482944/index.txt)

**Comment by frequenc1** [comment]
that index.txt file jsut copy and pasting contains errors. It seems as if your not closing the start method and all methods now live in side of it? Is that your intention?

**Comment by abataille** [comment]
I apologise for not answering. I just missed your question. The start method is closed. So, I had a missing bracket in the index.txt.
I noticed that you made some changes recently.  will test those in my environment and will come back in case I find issues.
Thanks
