### ISSUE TITLE
Understanding "type" and "id"

### ISSUE THREAD

**Issue by durera** [rainlake/node-lightify#10]
I was looking at the use of the type property in this library and the logic you have for determining capabilities of the lights ... e.g. 

```
    isBrightnessSupported : function(type) { return getNodeType(type) === 2 || getNodeType(type) === 4 || (getNodeType(type) != 16 && getNodeType(type) != 1);},
    isTemperatureSupported : function(type) {return getNodeType(type) === 2 || getNodeType(type) === 10; },
    isColorSupported : function(type) { return getNodeType(type) === 10 || getNodeType(type) === 8; },
    isLight : function(type) { return !isSwitch(type) && !isPlug(type) && !isSensor(type); },
```

- type 2 = a light that supports brightness + temp
- type 4 = a light that supports brightness only
- and so on

I was curious how you sussed these out, do you just have lots of different bulbs, or is there some documentation hidden away with this info in it somewhere?  I was wondering if these types are tied to the `ModelName` data available in the REST API (https://eu.lightify-api.org/lightify/api/json_devicevo.html) perhaps?  

I only have a set of P16TWs, which show as type 2, matching your capability check.  is there a 1:1 mapping between type and model perhaps?  Where `type = 2` means that the bulb is a P16TW, or would multiple different models of bulb with similar capabilities show up as type 2?

Similarly, do you happen to know what the value of `id` means?  All my bulbs have the same ID (65535), and I'm scratching my head trying to figure out what that actually means .. is this actually an ID of the model maybe (in this case where 65535 == P16TW)?

Great library by the way, such a shame the on-hub REST API is locked away from lightify home users and only available on the pro.  Seemed kind of silly writing code that ran on a pi in my house talking to an API in the cloud when the hub was sat 2ft away from it, and now I don't have to!

**Comment by rainlake** [comment]
the types define are  from lightify Android apk.
lightify bridge will report light bulb's type. I'm sure different models will report same type if they have same capacity
