### ISSUE TITLE
Command stack is growing

### ISSUE THREAD

**Issue by abataille** [rainlake/node-lightify#4]
I found the following:
When  i.e the brightness is changed with a slider control, a lot of commands are send with the new brightness value. It seems that the client write does not accept all of these. So the command stack goes with commands that were just not executed by the client.

**Comment by abataille** [comment]
Here to clarify what I found:
When I send to following commands in sequence, only some are really executed:
    lightify.node_on_off(mac, true);
    lightify.node_brightness(mac, 100);
    lightify.node_brightness(mac, 50);
    lightify.node_brightness(mac, 20);
    lightify.node_brightness(mac, 100);
    lightify.node_on_off(mac, false);
It seems that the client write the commands faster than Lightify can execute.
How can I cure that? Any idea?

**Comment by rainlake** [comment]
I recommend you use a setTimeout in your plugin. This module are supposed to send command directly to your gateway
