### ISSUE TITLE
HomeKit error controlling more than 2 lamps

### ISSUE THREAD

**Issue by dmckillican** [rainlake/node-lightify#7]
An error occurs when trying to control a room or group of lamps with more than 2 lamps attached. HomeKit will control 1, or 2 lamps in a group perfectly but will not control 3 or more lamps in a group. Where 3 or more lamps are grouped, only 1 lamp responds to commands. The lamp varies each time which suggests that the node may be sending all commands at the same time, but a slight buffer may be required.

If it is possible to resolve this issue I would be very grateful.

Thank you, Drew

**Comment by abataille** [comment]
This is the same as issue#4. Lightify hardware is quite slow. So when the Home app sends via Homebridge commands faster then Lightify can accept, some of the commands are lost.
So, a queue in needed that sends the commands in sequence one by one and waits until the previous command is executed.

**Comment by dmckillican** [comment]
Thanks for the reply. I understand your point, although it doesn't explain how and why the lightify gateway is capable of simultaneous light control. As the node is communicating with the gateway, and the gateway is issuing commands to the lights, the breakdown must be between the node and the gateway? either the node isn't sending the commands correctly, or the gateway isn't capable of receiving commands. Excuse my ignorance, but does the node use a different path to communicate with the gateway than the lightify app?

**Comment by rainlake** [comment]
The Lightify app itself can create on gateway. The group informations
stored on gateway, it only need one command to turn on/off all lights in
that group. HomeKit group is stored on you phone. Your phone have to send
multiple command to turn on/off each class in the group.

**Comment by rainlake** [comment]
I don't know which plug in are you using. I tested with my plugin https://github.com/rainlake/homebridge-platform-lightify without any issue for a group of three lights.
I created a scene with 3 lights. Click it in home app can turn all light on/off.

**Comment by rainlake** [comment]
I will close these issue since you did not responded. feel free to reopen.

**Comment by dmckillican** [comment]
Thanks for responding - I was away so wasn't able to get back to you sooner. I have moved from the homebridge-lightify plugin to your homebridge-platform-lightify plugin and it starts correctly, but won't pair with homekit. I've raised an issue  against homebridge-platform-lightify.

Your effort is greatly appreciated.
