### ISSUE TITLE
Lightify now supports temperature/motion sensors

### ISSUE THREAD

**Issue by apexad** [rainlake/node-lightify#8]
Lightify now supports zigbee motion/temperature sensors:
https://www.sylvania.com/en-us/products/new-products/Pages/LIGHTIFY®-Smart-Sensor.aspx
https://www.amazon.com/Sylvania-Lightify-Motion-Temperature-Sensor/
https://m.lowes.com/pd/Iris-Motion-Sensor-Works-with-Iris/999925310

They detect motion and also report the temperature. It would be great if you could add them to this utility so they can be used with the homebridge platform plugins.

**Comment by rainlake** [comment]
There is no plan to support these sensors.

**Comment by apexad** [comment]
At the very least, could they be excluded? They are incorrectly showing as a light with your homebridge plugin.

**Comment by rainlake** [comment]
Could you please attach your debug log? Thanks!

**Comment by apexad** [comment]
I will get it tonight.

**Comment by apexad** [comment]
I this what you want?

`Jan 26 22:07:22 alex-Hi-Fi-H81S2 homebridge[19726]: [1/26/2017, 10:07:22 PM] [Lightify] Lightify Light [A19 TW 60 01]
Jan 26 22:07:22 alex-Hi-Fi-H81S2 homebridge[19726]: [1/26/2017, 10:07:22 PM] [Lightify] Lightify Light [A19 W 60 03]
Jan 26 22:07:22 alex-Hi-Fi-H81S2 homebridge[19726]: [1/26/2017, 10:07:22 PM] [Lightify] Lightify Light [A19 W 60 01]
Jan 26 22:07:22 alex-Hi-Fi-H81S2 homebridge[19726]: [1/26/2017, 10:07:22 PM] [Lightify] Lightify Light [A19 W 60 02]
Jan 26 22:07:22 alex-Hi-Fi-H81S2 homebridge[19726]: [1/26/2017, 10:07:22 PM] [Lightify] Lightify Light [A19 W 60 04]
Jan 26 22:07:22 alex-Hi-Fi-H81S2 homebridge[19726]: [1/26/2017, 10:07:22 PM] [Lightify] Lightify Light [A19 TW 60 02]
Jan 26 22:07:22 alex-Hi-Fi-H81S2 homebridge[19726]: [1/26/2017, 10:07:22 PM] [Lightify] Lightify Light [Motion 01]
Jan 26 22:07:22 alex-Hi-Fi-H81S2 homebridge[19726]: [1/26/2017, 10:07:22 PM] [Lightify] Initializing platform accessory 'A19 TW 60 01'...
Jan 26 22:07:22 alex-Hi-Fi-H81S2 homebridge[19726]: [1/26/2017, 10:07:22 PM] [Lightify] Initializing platform accessory 'A19 W 60 03'...
Jan 26 22:07:22 alex-Hi-Fi-H81S2 homebridge[19726]: [1/26/2017, 10:07:22 PM] [Lightify] Initializing platform accessory 'A19 W 60 01'...
Jan 26 22:07:22 alex-Hi-Fi-H81S2 homebridge[19726]: [1/26/2017, 10:07:22 PM] [Lightify] Initializing platform accessory 'A19 W 60 02'...
Jan 26 22:07:22 alex-Hi-Fi-H81S2 homebridge[19726]: [1/26/2017, 10:07:22 PM] [Lightify] Initializing platform accessory 'A19 W 60 04'...
Jan 26 22:07:22 alex-Hi-Fi-H81S2 homebridge[19726]: [1/26/2017, 10:07:22 PM] [Lightify] Initializing platform accessory 'A19 TW 60 02'...
Jan 26 22:07:22 alex-Hi-Fi-H81S2 homebridge[19726]: [1/26/2017, 10:07:22 PM] [Lightify] Initializing platform accessory 'Motion 01'...`

**Comment by apexad** [comment]
I modified node-lightify as follows:
`    isLight : function(type) { console.log(type); return !isSwitch(type) && !isPlug(type); },`

and here is the output:
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: [1/26/2017, 10:26:15 PM] [Lightify] Discovered devices
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: 2
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: [1/26/2017, 10:26:15 PM] [Lightify] Lightify Light [A19 TW 60 01]
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: 4
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: [1/26/2017, 10:26:15 PM] [Lightify] Lightify Light [A19 W 60 03]
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: 4
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: [1/26/2017, 10:26:15 PM] [Lightify] Lightify Light [A19 W 60 01]
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: 4
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: [1/26/2017, 10:26:15 PM] [Lightify] Lightify Light [A19 W 60 02]
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: 4
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: [1/26/2017, 10:26:15 PM] [Lightify] Lightify Light [A19 W 60 04]
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: 64
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: 2
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: [1/26/2017, 10:26:15 PM] [Lightify] Lightify Light [A19 TW 60 02]
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: 32
Jan 26 22:26:15 alex-Hi-Fi-H81S2 homebridge[20034]: [1/26/2017, 10:26:15 PM] [Lightify] Lightify Light [Motion 01]

**Comment by rainlake** [comment]
Can you start homebridge with -D so I can have more information to get this device supported? Thanks!

**Comment by apexad** [comment]
Do you still need `homebridge -D` output?  Your 2.07 fix works fine.  Sensor no longer gets detected by HomeKit/Home App with your plugin.

This is perfect for me, because I've got the motion sensor setup to turn on my lights in the lightify app, so I am not concerned with seeing it in HomeKit.

**Comment by rainlake** [comment]
Yea please, I might be able to get this sensor supported. I temperary
removed sensor as your request. Thanks!

**Comment by rainlake** [comment]
Although you might not interested., Someone else may be. I will put a flag
in to disable sensor if you do not want show up

**Comment by apexad** [comment]
Sorry for the delay, hope this is what you want:

command sent [1][070000130100000001]
socket data: [9901011301000000000800da132e23020000261884020102040302010000648e0a010000ff4131392054572036302030310000000000000000000000008688d22aa000aa3eb07c040102040302020000640000010000ff41313920572036302030330000000000000000000000000018e03138a000aa3eb07c040102040102020000640000010000ff4131392057203630203031000000000000000000000000007e779c42a000aa3eb07c040102040102020000640000010000ff4131392057203630203032000000000000000000000000000807a32fa000aa3eb07c0401020403020400000b0000010000ff413139205720363020303400000000000000000000000000e30c5ccae80000261884401000510102000001640000010000ff44696d6d696e675377697463683031000000000000000000acc35b8e060000261884020102049202080000328e0a010000ff413139205457203630203032000000000000000000000000ee7e237a6505006f0d00201100530002000001640000010000ff4d6f74696f6e203031000000000000000000000000000000]
Expected len [411]
len = [411]
got response for seq [1][9901011301000000000800da132e23020000261884020102040302010000648e0a010000ff4131392054572036302030310000000000000000000000008688d22aa000aa3eb07c040102040302020000640000010000ff41313920572036302030330000000000000000000000000018e03138a000aa3eb07c040102040102020000640000010000ff4131392057203630203031000000000000000000000000007e779c42a000aa3eb07c040102040102020000640000010000ff4131392057203630203032000000000000000000000000000807a32fa000aa3eb07c0401020403020400000b0000010000ff413139205720363020303400000000000000000000000000e30c5ccae80000261884401000510102000001640000010000ff44696d6d696e675377697463683031000000000000000000acc35b8e060000261884020102049202080000328e0a010000ff413139205457203630203032000000000000000000000000ee7e237a6505006f0d00201100530002000001640000010000ff4d6f74696f6e203031000000000000000000000000000000]

**Comment by apexad** [comment]
Any progress on this? Just want to confirm that is the data you needed?

**Comment by rainlake** [comment]
I thought about it recently, I think there is nothing we can do because there is no "notification" from bridge when motion is detected. we are polling from bridge every 30 secs.
I did find something interesting that bridge might do groupcast, I will do more research.
